const ACTION = Object.freeze({
  //--- editor
  _OPEN_MODAL_EDITOR: 'OPEN_MODAL_EDITOR',
  _CLOSE_MODAL_EDITOR: 'CLOSE_MODAL_EDITOR',
  _OPEN_EMBEDDED_EDITOR: 'OPEN_EMBEDDED_EDITOR',
  _CLOSE_EMBEDDED_EDITOR: 'CLOSE_EMBEDDED_EDITOR',
  //--- database
  _ADD: 'ADD',
  _UPDATE: 'UPDATE',
  _DELETE: 'DELETE',
  //--- display_period
  _SET_PERIOD_TYPE: 'SET_PERIOD_TYPE',
  _SET_PERIOD: 'SET_PERIOD',
  _SHIFT_PERIOD: 'SHIFT_PERIOD',
  //--- display
  _RELOAD: 'RELOAD',
  _RENDER: 'RENDER',
  _RE_RENDER: 'RE_RENDER',
  _HIDE: 'HIDE',
  _SELECT: 'SELECT',
  _SORT: 'SORT',
});

export default ACTION;
