const OPERATION = Object.freeze({
  _ADD: 'ADD',
  _UPDATE: 'UPDATE',
  _UPDATE_STATUS: 'UPDATE_STATUS',
  _DELETE: 'DELETE',
  _SELECT: 'SELECT',
  _SORT: 'SORT',
  _SET_RANGE: '_SET_RANGE',
  _SHIFT_RANGE: 'SHIFT_RANGE',
  _DISPLAY: 'DISPLAY',
  _UPDATE_DISPLAY: 'UPDATE_DISPLAY',
  _DELETE_DISPLAY: 'DELETE_DISPLAY',
});

export default OPERATION;
