const OPERATION = Object.freeze({
  _ADD: 'ADD',
  _UPDATE: 'UPDATE',
  _UPDATE_STATUS: 'UPDATE_STATUS',
  _DELETE: 'DELETE',
  _SELECT: 'SELECT',
  _SORT: 'SORT',
  _SWITCH_FILTER: 'SWITCH_FILTER',
});

export default OPERATION;
